"""Read-only API for measured model evaluation results.

Evaluation numbers are loaded from reports generated by the ML training pipeline.
The API never computes or ranks a model and never declares a production winner.
"""
from __future__ import annotations
from fastapi import Depends
from app.core.security import require_roles

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Query

router = APIRouter(prefix="/models", tags=["AI Models"])

PROJECT_ROOT = Path(__file__).resolve().parents[5]
REPORTS_ROOT = PROJECT_ROOT / "reports" / "ml"
SUPPORTED_DATASETS = ("cicids2017", "cicids2018", "nsl-kdd")
SUPPORTED_TASKS = ("binary", "multiclass")
COMPARED_MODELS = ("random_forest", "xgboost")


def _load_run(report_dir: Path) -> dict[str, Any]:
    metrics = json.loads((report_dir / "metrics.json").read_text())
    run_info_path = report_dir / "run_info.json"
    run_info = json.loads(run_info_path.read_text()) if run_info_path.exists() else {}
    auc = metrics.get("roc_auc") or {}
    return {
        "dataset": report_dir.parts[-3],
        "task": report_dir.parts[-2],
        "model": report_dir.parts[-1],
        "n_samples": metrics.get("n_samples"),
        "average": metrics.get("average"),
        "accuracy": metrics.get("accuracy"),
        "precision": metrics.get("precision"),
        "recall": metrics.get("recall"),
        "f1_score": metrics.get("f1_score"),
        "balanced_accuracy": metrics.get("balanced_accuracy"),
        "roc_auc": auc.get("binary") if "binary" in auc else auc.get("macro_ovr"),
        "average_precision": auc.get("average_precision"),
        "classification_report": metrics.get("classification_report"),
        "confusion_matrix": metrics.get("confusion_matrix"),
        "support": metrics.get("support"),
        "created_at_utc": run_info.get("created_at_utc"),
        "available_files": sorted(
            p.name for p in report_dir.iterdir()
            if p.is_file() and p.name in {
                "metrics.json", "classification_report.json", "classification_report.txt",
                "confusion_matrix.csv", "confusion_matrix_normalized.csv", "confusion_matrix.png",
                "roc_curve.csv", "roc_curve.png",
                "precision_recall_curve.csv", "precision_recall_curve.png",
            }
        ),
    }


def _curve(report_dir: Path, filename: str) -> list[dict[str, float]]:
    path = report_dir / filename
    if not path.exists():
        return []
    import csv
    with path.open(newline="") as fh:
        return [{k: float(v) for k, v in row.items() if v not in ("", "nan", "NaN")} for row in csv.DictReader(fh)]


def _find(dataset: str, task: str, model: str) -> Path:
    if dataset not in SUPPORTED_DATASETS or task not in SUPPORTED_TASKS or model not in COMPARED_MODELS:
        raise HTTPException(status_code=404, detail="Unsupported dataset, task, or comparison model")
    path = REPORTS_ROOT / dataset / task / model
    if not (path / "metrics.json").exists():
        raise HTTPException(status_code=404, detail="Evaluation results have not been generated for this combination")
    return path


@router.get("/evaluations")
def list_evaluations(
    dataset: str | None = Query(default=None),
    task: str | None = Query(default=None),
) -> dict[str, Any]:
    """Return measured Random Forest/XGBoost results for all available dataset/task runs."""
    if dataset and dataset not in SUPPORTED_DATASETS:
        raise HTTPException(status_code=400, detail="Unsupported dataset")
    if task and task not in SUPPORTED_TASKS:
        raise HTTPException(status_code=400, detail="Unsupported task")

    results: list[dict[str, Any]] = []
    if REPORTS_ROOT.exists():
        for ds in SUPPORTED_DATASETS:
            if dataset and ds != dataset:
                continue
            for tk in SUPPORTED_TASKS:
                if task and tk != task:
                    continue
                for model in COMPARED_MODELS:
                    path = REPORTS_ROOT / ds / tk / model
                    if (path / "metrics.json").exists():
                        results.append(_load_run(path))
    return {
        "comparison_models": list(COMPARED_MODELS),
        "supported_datasets": list(SUPPORTED_DATASETS),
        "supported_tasks": list(SUPPORTED_TASKS),
        "results": results,
        "selection_policy": "Measured results only. No universal best model is selected by the system; the project administrator chooses the production model using documented criteria.",
    }


@router.get("/evaluations/{dataset}/{task}/{model}")
def get_evaluation(dataset: str, task: str, model: str, user=Depends(require_roles('administrator', 'analyst', 'viewer'))) -> dict[str, Any]:
    path = _find(dataset, task, model)
    result = _load_run(path)
    result["roc_curve"] = _curve(path, "roc_curve.csv")
    result["precision_recall_curve"] = _curve(path, "precision_recall_curve.csv")
    return result
