"""Create initial PostgreSQL application schema."""
from alembic import op
import sqlalchemy as sa

revision = '0001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('users', sa.Column('id', sa.String(36), primary_key=True), sa.Column('email', sa.String(320), nullable=False, unique=True), sa.Column('password_hash', sa.String(255)), sa.Column('role', sa.String(50), nullable=False, server_default='analyst'), sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('datasets', sa.Column('id', sa.String(100), primary_key=True), sa.Column('name', sa.String(200), nullable=False), sa.Column('version', sa.String(100)), sa.Column('description', sa.Text()), sa.Column('metadata_json', sa.JSON()), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('models', sa.Column('id', sa.String(36), primary_key=True), sa.Column('dataset_id', sa.String(100), sa.ForeignKey('datasets.id', ondelete='CASCADE'), nullable=False), sa.Column('name', sa.String(100), nullable=False), sa.Column('task', sa.String(50), nullable=False), sa.Column('artifact_key', sa.String(255), nullable=False), sa.Column('version', sa.String(100)), sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column('metrics', sa.JSON()), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('ix_models_dataset_task_name', 'models', ['dataset_id','task','name'], unique=True)
    op.create_table('detections', sa.Column('id', sa.String(36), primary_key=True), sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL')), sa.Column('dataset_id', sa.String(100), sa.ForeignKey('datasets.id', ondelete='RESTRICT'), nullable=False), sa.Column('model_id', sa.String(36), sa.ForeignKey('models.id', ondelete='RESTRICT'), nullable=False), sa.Column('prediction', sa.String(255), nullable=False), sa.Column('prediction_index', sa.Integer(), nullable=False), sa.Column('probability', sa.Float(), nullable=False), sa.Column('probabilities', sa.JSON(), nullable=False), sa.Column('raw_features', sa.JSON(), nullable=False), sa.Column('original_feature_values', sa.JSON()), sa.Column('transformed_features', sa.JSON()), sa.Column('feature_names', sa.JSON()), sa.Column('explanation_status', sa.JSON()), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('ix_detections_user_id','detections',['user_id']); op.create_index('ix_detections_dataset_id','detections',['dataset_id']); op.create_index('ix_detections_model_id','detections',['model_id']); op.create_index('ix_detections_created_at','detections',['created_at']); op.create_index('ix_detections_prediction','detections',['prediction'])
    op.create_table('alerts', sa.Column('id', sa.String(36), primary_key=True), sa.Column('detection_id', sa.String(36), sa.ForeignKey('detections.id', ondelete='CASCADE'), nullable=False), sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL')), sa.Column('severity', sa.String(30), nullable=False), sa.Column('status', sa.String(30), nullable=False, server_default='open'), sa.Column('message', sa.Text(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False)); op.create_index('ix_alerts_detection_id','alerts',['detection_id']); op.create_index('ix_alerts_user_id','alerts',['user_id'])
    op.create_table('explanations', sa.Column('id', sa.String(36), primary_key=True), sa.Column('detection_id', sa.String(36), sa.ForeignKey('detections.id', ondelete='CASCADE'), nullable=False), sa.Column('method', sa.String(30), nullable=False), sa.Column('payload', sa.JSON(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False)); op.create_index('ix_explanations_detection_id','explanations',['detection_id']); op.create_index('ix_explanations_detection_method','explanations',['detection_id','method'], unique=True)
    op.create_table('response_actions', sa.Column('id', sa.String(36), primary_key=True), sa.Column('detection_id', sa.String(36), sa.ForeignKey('detections.id', ondelete='CASCADE'), nullable=False), sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL')), sa.Column('action_type', sa.String(100), nullable=False), sa.Column('status', sa.String(30), nullable=False, server_default='pending'), sa.Column('details', sa.JSON()), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False)); op.create_index('ix_response_actions_detection_id','response_actions',['detection_id']); op.create_index('ix_response_actions_user_id','response_actions',['user_id'])
    op.create_table('reports', sa.Column('id', sa.String(36), primary_key=True), sa.Column('user_id', sa.String(36), sa.ForeignKey('users.id', ondelete='SET NULL')), sa.Column('detection_id', sa.String(36), sa.ForeignKey('detections.id', ondelete='SET NULL')), sa.Column('report_type', sa.String(100), nullable=False), sa.Column('status', sa.String(30), nullable=False, server_default='generated'), sa.Column('storage_key', sa.String(500)), sa.Column('metadata_json', sa.JSON()), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False)); op.create_index('ix_reports_user_id','reports',['user_id']); op.create_index('ix_reports_detection_id','reports',['detection_id'])

def downgrade():
    for t in ['reports','response_actions','explanations','alerts','detections','models','datasets','users']:
        op.drop_table(t)
